#!/bin/sh
#
# Script to install a debug build of the sample raster driver.
#
# Uses xcodebuild.
#

# Install into /...
sudo xcodebuild -target ImageWriterII -configuration Debug install DSTROOT=/

sudo launchctl stop org.cups.cupsd
sudo launchctl start org.cups.cupsd
